name: Web3App.agency Website Workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Run-Linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.0]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn install
      - name: Run ESLint
        run: yarn lint:code
      - name: Run stylelint
        run: yarn lint:styles
      - name: Build ProcessNext.js App
        run: yarn build